// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Athlete struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Grade string `json:"grade"`
	Event string `json:"event"`
	Pr    string `json:"pr"`
}

type Meet struct {
	ID       int32     `json:"id"`
	Name     string    `json:"name"`
	Date     time.Time `json:"date"`
	Location string    `json:"location"`
}

type Result struct {
	ID        int32  `json:"id"`
	AthleteID int32  `json:"athleteId"`
	MeetID    int32  `json:"meetId"`
	Time      string `json:"time"`
	Place     int32  `json:"place"`
}
