// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createResult = `-- name: CreateResult :execlastid
INSERT INTO results (athlete_id, meet_id, time, place)
VALUES (?, ?, ?, ?)
`

type CreateResultParams struct {
	AthleteID int32  `json:"athleteId"`
	MeetID    int32  `json:"meetId"`
	Time      string `json:"time"`
	Place     int32  `json:"place"`
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getAllAthletes = `-- name: GetAllAthletes :many
SELECT id, name, grade, event, pr FROM athletes
`

func (q *Queries) GetAllAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getAllAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.Event,
			&i.Pr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMeets = `-- name: GetAllMeets :many
SELECT id, name, date, location FROM meets ORDER BY date ASC
`

func (q *Queries) GetAllMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, event, pr FROM athletes WHERE id = ?
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.Event,
		&i.Pr,
	)
	return i, err
}

const getMeetResults = `-- name: GetMeetResults :many
SELECT r.id, r.athlete_id, a.name AS athlete_name, r.meet_id, r.time, r.place
FROM results r
JOIN athletes a ON a.id = r.athlete_id
WHERE r.meet_id = ?
`

type GetMeetResultsRow struct {
	ID          int32  `json:"id"`
	AthleteID   int32  `json:"athleteId"`
	AthleteName string `json:"athleteName"`
	MeetID      int32  `json:"meetId"`
	Time        string `json:"time"`
	Place       int32  `json:"place"`
}

func (q *Queries) GetMeetResults(ctx context.Context, meetID int32) ([]GetMeetResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMeetResults, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeetResultsRow
	for rows.Next() {
		var i GetMeetResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.AthleteName,
			&i.MeetID,
			&i.Time,
			&i.Place,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTimes = `-- name: GetTopTimes :many
SELECT r.id, r.athlete_id, a.name AS athlete_name, r.meet_id, m.name AS meet_name, r.time, r.place
FROM results r
JOIN athletes a ON a.id = r.athlete_id
JOIN meets m ON m.id = r.meet_id
ORDER BY r.time ASC
LIMIT 10
`

type GetTopTimesRow struct {
	ID          int32  `json:"id"`
	AthleteID   int32  `json:"athleteId"`
	AthleteName string `json:"athleteName"`
	MeetID      int32  `json:"meetId"`
	MeetName    string `json:"meetName"`
	Time        string `json:"time"`
	Place       int32  `json:"place"`
}

const getAllResults = `-- name: GetAllResults :many
SELECT r.id, r.athlete_id, a.name AS athlete_name, r.meet_id, m.name AS meet_name, r.time, r.place
FROM results r
JOIN athletes a ON a.id = r.athlete_id
JOIN meets m ON m.id = r.meet_id
ORDER BY r.meet_id ASC, r.place ASC
`

func (q *Queries) GetAllResults(ctx context.Context) ([]GetTopTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTimesRow
	for rows.Next() {
		var i GetTopTimesRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.AthleteName,
			&i.MeetID,
			&i.MeetName,
			&i.Time,
			&i.Place,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAthlete = `-- name: UpdateAthlete :exec
UPDATE athletes SET name = ?, grade = ?, event = ?, pr = ? WHERE id = ?
`

type UpdateAthleteParams struct {
	Name  string `json:"name"`
	Grade string `json:"grade"`
	Event string `json:"event"`
	Pr    string `json:"pr"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateAthlete(ctx context.Context, arg UpdateAthleteParams) error {
	_, err := q.db.ExecContext(ctx, updateAthlete, arg.Name, arg.Grade, arg.Event, arg.Pr, arg.ID)
	return err
}

const deleteAthlete = `-- name: DeleteAthlete :exec
DELETE FROM athletes WHERE id = ?
`

func (q *Queries) DeleteAthlete(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAthlete, id)
	return err
}

const updateMeet = `-- name: UpdateMeet :exec
UPDATE meets SET name = ?, date = ?, location = ? WHERE id = ?
`

type UpdateMeetParams struct {
	Name     string    `json:"name"`
	Date     time.Time `json:"date"`
	Location string    `json:"location"`
	ID       int32     `json:"id"`
}

func (q *Queries) UpdateMeet(ctx context.Context, arg UpdateMeetParams) error {
	_, err := q.db.ExecContext(ctx, updateMeet, arg.Name, arg.Date, arg.Location, arg.ID)
	return err
}

const deleteMeet = `-- name: DeleteMeet :exec
DELETE FROM meets WHERE id = ?
`

func (q *Queries) DeleteMeet(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMeet, id)
	return err
}

const createAthlete = `INSERT INTO athletes (name, grade, event, pr) VALUES (?, ?, ?, ?)`

type CreateAthleteParams struct {
	Name  string `json:"name"`
	Grade string `json:"grade"`
	Event string `json:"event"`
	Pr    string `json:"pr"`
}

func (q *Queries) CreateAthlete(ctx context.Context, arg CreateAthleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAthlete, arg.Name, arg.Grade, arg.Event, arg.Pr)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createMeet = `INSERT INTO meets (name, date, location) VALUES (?, ?, ?)`

type CreateMeetParams struct {
	Name     string    `json:"name"`
	Date     time.Time `json:"date"`
	Location string    `json:"location"`
}

func (q *Queries) CreateMeet(ctx context.Context, arg CreateMeetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMeet, arg.Name, arg.Date, arg.Location)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

func (q *Queries) GetTopTimes(ctx context.Context) ([]GetTopTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTimesRow
	for rows.Next() {
		var i GetTopTimesRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.AthleteName,
			&i.MeetID,
			&i.MeetName,
			&i.Time,
			&i.Place,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
