// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createResult = `-- name: CreateResult :execlastid
INSERT INTO results (athlete_id, meet_id, time, place)
VALUES (?, ?, ?, ?)
`

type CreateResultParams struct {
	AthleteID int32  `json:"athleteId"`
	MeetID    int32  `json:"meetId"`
	Time      string `json:"time"`
	Place     int32  `json:"place"`
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getAllAthletes = `-- name: GetAllAthletes :many
SELECT id, name, grade, event, pr FROM athletes
`

func (q *Queries) GetAllAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getAllAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.Event,
			&i.Pr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMeets = `-- name: GetAllMeets :many
SELECT id, name, date, location FROM meets ORDER BY date ASC
`

func (q *Queries) GetAllMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, event, pr FROM athletes WHERE id = ?
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.Event,
		&i.Pr,
	)
	return i, err
}

const getMeetResults = `-- name: GetMeetResults :many
SELECT r.id, r.athlete_id, a.name AS athlete_name, r.meet_id, r.time, r.place
FROM results r
JOIN athletes a ON a.id = r.athlete_id
WHERE r.meet_id = ?
`

type GetMeetResultsRow struct {
	ID          int32  `json:"id"`
	AthleteID   int32  `json:"athleteId"`
	AthleteName string `json:"athleteName"`
	MeetID      int32  `json:"meetId"`
	Time        string `json:"time"`
	Place       int32  `json:"place"`
}

func (q *Queries) GetMeetResults(ctx context.Context, meetID int32) ([]GetMeetResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMeetResults, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeetResultsRow
	for rows.Next() {
		var i GetMeetResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.AthleteName,
			&i.MeetID,
			&i.Time,
			&i.Place,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopTimes = `-- name: GetTopTimes :many
SELECT r.id, r.athlete_id, a.name AS athlete_name, r.meet_id, m.name AS meet_name, r.time, r.place
FROM results r
JOIN athletes a ON a.id = r.athlete_id
JOIN meets m ON m.id = r.meet_id
ORDER BY r.time ASC
LIMIT 10
`

type GetTopTimesRow struct {
	ID          int32  `json:"id"`
	AthleteID   int32  `json:"athleteId"`
	AthleteName string `json:"athleteName"`
	MeetID      int32  `json:"meetId"`
	MeetName    string `json:"meetName"`
	Time        string `json:"time"`
	Place       int32  `json:"place"`
}

func (q *Queries) GetTopTimes(ctx context.Context) ([]GetTopTimesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopTimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopTimesRow
	for rows.Next() {
		var i GetTopTimesRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.AthleteName,
			&i.MeetID,
			&i.MeetName,
			&i.Time,
			&i.Place,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
